apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiftmessageparser
spec:
  selector:
    matchLabels:
      app: swiftmessageparser
  replicas: 3
  template:
    metadata:
      labels:
        app: swiftmessageparser
    spec:
      containers:
        - name: swiftmessageparser
          image: docker.io/5c7270c2/9ac12a0d:swiftmessageparser
          ports:
            - containerPort: 8080
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf # name of configMap
                  key: host
            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: name
            - name: POSTGRES_USER  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials # Secret Name
                  key: postgres_user
            - name: POSTGRES_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_password
---
apiVersion: v1
kind: Service
metadata:
  name: swiftmessageparser-service
spec:
  type: NodePort
  selector:
    app: swiftmessageparser
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007