version: '2'

services:
  app:
    image: 'swiftmessageparser'
    ports:
      - "8080:8080"
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=bechir
      - SPRING_DATASOURCE_PASSWORD=98305955Amel
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
          
  db:
    image: 'postgres:12.8'
    ports:
    - 127.0.0.1:5432:5432/tcp
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=98305955Amel